apiVersion: v1
kind: Pod
metadata:
  name: missing-app-name-label
  namespace: demo
  labels:
    app.kubernetes.io/part-of: istio-demo
    app.kubernetes.io/name: frontend
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.10
