apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  labels:
    app.kubernetes.io/name: root
    app.kubernetes.io/part-of: local-platform
spec:
  project: default
  source:
    repoURL: __REPO_URL__
    targetRevision: __TARGET_REVISION__
    path: apps/root-app
    helm:
      parameters:
        - name: repoURL
          value: __REPO_URL__
        - name: targetRevision
          value: __TARGET_REVISION__
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

