apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: kyverno-policies
    app.kubernetes.io/part-of: local-platform
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: platform/kyverno/policies
    directory:
      recurse: true
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

