apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-kubernetes-auth-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: vault-kubernetes-auth-rbac
    app.kubernetes.io/part-of: local-platform
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: platform/vault/manifests
    directory:
      recurse: true
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

