apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-demo-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    app.kubernetes.io/name: vault-demo-secrets
    app.kubernetes.io/part-of: local-platform
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: manifests/vault-demo-secrets
    directory:
      recurse: true
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
