apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: local-platform
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: demo-reader
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
            audiences:
              - vault

