apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-config
  namespace: demo
  labels:
    app.kubernetes.io/name: demo-config
    app.kubernetes.io/part-of: local-platform
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: demo-config
    creationPolicy: Owner
  data:
    - secretKey: message
      remoteRef:
        key: demo/config
        property: message
    - secretKey: username
      remoteRef:
        key: demo/config
        property: username

